server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/union?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: tester
    password: tester
    driver-class-name: com.mysql.cj.jdbc.Driver