server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/union?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: tester
    password: tester
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false    #缓冲的配置
#      check-template: true
#      check-template-location: true
#      #开启MVC thymeleaf 视图解析
#      enabled: true
#      encoding: utf-8
#      mode: HTML5
#      prefix: classpath:/templates/
#      suffix: .html

  #ueditor配置
  mvc:
      static-path-pattern: '/**'
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.union.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#ueditor配置
web:
    upload-path: 'E:/union/src/main/resources/static/pictures/'